question_data = [
    {
        "category": "Entertainment: Video Games",
        "type": "boolean",
        "difficulty": "easy",
        "question": "Donkey Kong was originally set to be a Popeye arcade game.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "General Knowledge",
        "type": "boolean",
        "difficulty": "medium",
        "question": "The French word to travel is Travail;",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "General Knowledge",
        "type": "boolean",
        "difficulty": "easy",
        "question": "When you cry in space, your tears stick to your face.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "General Knowledge",
        "type": "boolean",
        "difficulty": "easy",
        "question": "One of Donald Trump&#039;s 2016 Presidential Campaign promises was to build a border wall between the United States and Mexico.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Entertainment: Board Games",
        "type": "boolean",
        "difficulty": "easy",
        "question": "&quot;PAYDAY: The Heist&quot; is a sequel to the board game &quot;Payday&quot;.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "General Knowledge",
        "type": "boolean",
        "difficulty": "hard",
        "question": "Stagecoach owned &quot;South West Trains&quot; before losing the rights to FirstGroup and MTR in March of 2017.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Entertainment: Music",
        "type": "boolean",
        "difficulty": "easy",
        "question": "The 2011 movie &quot;The Adventures of Tintin&quot; was directed by Steven Spielberg.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "General Knowledge",
        "type": "boolean",
        "difficulty": "medium",
        "question": "Popcorn was invented in 1871 by Frederick W. Rueckheim in the USA where he sold the snack on the streets of Chicago.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "category": "General Knowledge",
        "type": "boolean",
        "difficulty": "easy",
        "question": "Jingle Bells was originally meant for Thanksgiving",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "category": "Entertainment: Video Games",
        "type": "boolean",
        "difficulty": "easy",
        "question": "&quot;Resident Evil 7&quot; is the first first-person Resident Evil game.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
]
